# Use root/example as user/password credentials
version: '3.1'

services:
  web:
    build: ./web
    restart: always
    ports: 
      - 5000:5000

  db:
#if we need build from dockerfile in folder    
# build: ./db 
    image: mariadb
    restart: always
    environment:
#see .env      
# MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: 123456
# MOUNT LOCAL STORAGE FROM SERVER
    volumes: 
      - ./database:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 9091:8080