# Use root/example as user/password credentials
version: '3.1'

services:

  db:
# build: ./db 
    image: mariadb
    restart: always
    environment:
# MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: 123456
    volumes: 
      - ./database:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080